# Generated by Django 2.2.3 on 2019-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('decription_category', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
    ]
