# Generated by Django 2.2.3 on 2019-07-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190730_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_category',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=128, verbose_name='Название товара')),
                ('description_product', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price_product', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Categories')),
            ],
        ),
    ]
