# Generated by Django 2.2.3 on 2019-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, upload_to='images_products'),
        ),
    ]
