# Generated by Django 2.2.3 on 2019-07-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190730_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='header_category',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок категории'),
        ),
    ]
