# Generated by Django 2.2.3 on 2019-07-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_categories_link_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='link_category',
            field=models.CharField(blank=True, default='/', max_length=128, verbose_name='Ссылка категории'),
        ),
    ]
