# Generated by Django 2.2.4 on 2019-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190731_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_page', models.CharField(max_length=128, unique=True, verbose_name='Название страницы')),
                ('header_page', models.CharField(blank=True, max_length=128, verbose_name='Заголовок страницы')),
                ('content_page', models.TextField(blank=True, default='<p></p>', verbose_name='Контент страницы')),
                ('show_in_main_menu', models.BooleanField(default=False, verbose_name='Выводить страницу в главном меню?')),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='link_category',
        ),
        migrations.AddField(
            model_name='categories',
            name='show_in_main_menu',
            field=models.BooleanField(default=False, verbose_name='Выводить страницу в главном меню?'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Товар со скидкой'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Эксклюзивный товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
    ]
