# Generated by Django 2.2.4 on 2019-08-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190817_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['is_active', 'name_category'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='infopages',
            options={'ordering': ['name_page'], 'verbose_name': 'Инфостраница', 'verbose_name_plural': 'Информационные страницы'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['is_active', 'name_product'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Кол-во на складе'),
        ),
    ]
