# Generated by Django 2.2.4 on 2019-08-29 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20190824_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuserprofile',
            options={'ordering': ['user'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей в соцсетях'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 12, 33, 317010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Выберите пол'), ('M', 'мужчина'), ('W', 'женщина')], max_length=1, verbose_name='Пол'),
        ),
    ]
